(() => {
  const K={dados:"orc_dados",logo:"orc_logo",produtos:"orc_produtos",orcamentos:"orc_orcamentos",backupDias:"orc_backup_dias",backupUltimo:"orc_backup_ultimo",senha:"orc_senha"};
  const $=id=>document.getElementById(id);
  const json=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f));}catch{return f;}};
  const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
  const fmt=v=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
  const esc=v=>String(v||"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
  const dataBR=iso=>iso?new Date(iso).toLocaleString("pt-BR"):"";
  const cleanPix=t=>String(t||"").replace(/\n💸 \*Pix:\*/g,"\n*Pix:*").replace(/\n💸 Pix:/g,"\nPix:").replace(/💸 \*Pix:\*/g,"*Pix:*").replace(/💸 Pix:/g,"Pix:");

  function style(){const s=document.createElement("style");s.textContent=`.hist-list,.prod-list{display:flex;flex-direction:column;gap:10px;margin-top:10px}.hist-card,.prod-row,.prod-picker,.backup-box{background:#FFF9FC;border:1px solid #F2EAF8;border-radius:16px;padding:12px}.hist-card{box-shadow:0 5px 14px rgba(0,0,0,.04)}.hist-top{display:flex;justify-content:space-between;gap:10px;align-items:flex-start}.hist-title{font-size:13px;font-weight:800;color:#7a3a6b}.hist-meta,.hist-text,.backup-small,.backup-box p,.backup-box li{font-size:11px;color:#7a6c9f;line-height:1.55}.hist-total{font-size:12px;font-weight:800;color:#8C7BFF;white-space:nowrap}.hist-text{white-space:pre-wrap;background:#fff;border-radius:12px;padding:10px;margin-top:8px;display:none}.hist-actions,.backup-actions,.prod-actions,.pix-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:10px}.hist-actions button,.backup-actions button,.prod-picker button,.prod-actions button,.pix-actions button{border:none;border-radius:999px;padding:10px;font-size:11px;font-weight:700;cursor:pointer;background:#F0EDFF;color:#8C7BFF;font-family:'Poppins',sans-serif;min-height:38px;line-height:1.2;white-space:normal}.hist-actions .danger,.prod-actions .danger{background:#FFE4E4;color:#c73232}.hist-empty{font-size:12px;color:#a08fc7;text-align:center;background:#FFF9FC;border-radius:14px;padding:16px}.backup-box ul{padding-left:18px;margin:8px 0}.backup-actions input[type=file]{grid-column:1/-1;border-radius:14px;font-size:12px;background:#fff}.prod-picker{margin:8px 0 12px}.prod-picker-title{font-size:12px;font-weight:800;color:#7a3a6b;margin-bottom:8px}.prod-picker-grid{display:grid;grid-template-columns:1fr 76px;gap:8px;align-items:end}.prod-picker button{grid-column:1/-1;padding:11px;font-size:12px}.prod-picker .hint{grid-column:1/-1;margin-top:2px}.prod-row{display:block;font-size:12px;color:#7a6c9f}.prod-row strong{color:#7a3a6b}.prod-search{margin-bottom:10px}.prod-actions{grid-template-columns:1fr}.prod-actions .danger{max-width:130px}.pix-actions{margin-top:-4px;margin-bottom:12px}`;document.head.appendChild(s);}
  function activate(tab,panel){document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".panel").forEach(p=>p.classList.remove("active"));tab.classList.add("active");panel.classList.add("active");}
  function tab(id,label,before){const tabs=document.querySelector(".tabs"),main=document.querySelector("main");if(!tabs||!main||$(`panel${id}`))return null;const t=document.createElement("div");t.className="tab";t.dataset.tab=id.toLowerCase();t.textContent=label;tabs.insertBefore(t,tabs.querySelector(before));const p=document.createElement("div");p.id=`panel${id}`;p.className="panel";main.insertBefore(p,$("panelDados"));t.onclick=()=>{activate(t,p);if(id==="Historico")renderHistory();if(id==="Produtos")renderProducts();};return p;}
  function ensureProductsTab(){const p=tab("Produtos","Produtos",'[data-tab="dados"]');if(!p)return;const old=$("btnSalvarProduto")?.closest(".dados-card");p.innerHTML=`<div class="dados-card"><div class="sec-title">Produtos cadastrados</div><div class="fgroup prod-search"><label class="lbl">Buscar produto</label><input type="text" id="prodBusca" placeholder="Digite para buscar"></div><div id="prodCadastroSlot"></div><div class="prod-list" id="produtosTabList"></div></div>`;if(old)$("prodCadastroSlot").appendChild(old);$("prodBusca").oninput=renderProducts;renderProducts();}
  function ensureHistoryTab(){const p=tab("Historico","Histórico",'[data-tab="dados"]');if(!p)return;p.innerHTML=`<div class="fcard"><div class="sec-title">Catálogo de orçamentos</div><div class="fgroup"><label class="lbl">Buscar por cliente, tema ou item</label><input type="text" id="histBusca" placeholder="Digite para buscar"></div><div class="hist-list" id="histList"></div></div>`;$("histBusca").oninput=renderHistory;}
  function ensurePicker(){if($("prodPicker"))return;const list=$("iList");if(!list)return;const b=document.createElement("div");b.id="prodPicker";b.className="prod-picker";b.innerHTML=`<div class="prod-picker-title">Inserir produto cadastrado</div><div class="prod-picker-grid"><div><label class="mini-label">Produto salvo</label><select id="prodEscolhido"></select></div><div><label class="mini-label">Qtd.</label><input type="number" id="prodQtd" min="1" step="1" value="1"></div><button type="button" id="btnInserirProduto">Inserir no orçamento</button><p class="hint">Escolha um produto cadastrado ou comece a digitar no campo Produtos para autopreencher.</p></div>`;list.parentElement.insertBefore(b,list);$("btnInserirProduto").onclick=insertSelected;renderProductSelect(true);}
  function renderProductSelect(blank=false){const s=$("prodEscolhido");if(!s)return;const ps=json(K.produtos,[]);s.innerHTML=`<option value="">Escolha um produto</option>`+ps.map((p,i)=>`<option value="${i}">${esc(p.nome)} - ${fmt(p.valor)}</option>`).join("");if(blank)s.value="";}
  function renderProducts(){const box=$("produtosTabList");if(!box)return;const q=($("prodBusca")?.value||"").toLowerCase();const ps=json(K.produtos,[]).map((p,i)=>({...p,i})).filter(p=>!q||String(p.nome).toLowerCase().includes(q));renderProductSelect();if(!ps.length){box.innerHTML='<div class="hist-empty">Nenhum produto cadastrado ainda.</div>';return;}box.innerHTML="";ps.forEach(p=>{const r=document.createElement("div");r.className="prod-row";r.innerHTML=`<strong>${esc(p.nome)}</strong><br>${fmt(p.valor)}<div class="prod-actions"><button type="button" data-a="usar">Usar no orçamento</button><button type="button" class="danger" data-a="excluir">Excluir</button></div>`;r.querySelector('[data-a="usar"]').onclick=()=>useProduct(p.i);r.querySelector('[data-a="excluir"]').onclick=()=>deleteProduct(p.i);box.appendChild(r);});}
  function deleteProduct(i){if(!confirm("Excluir este produto cadastrado?"))return;const ps=json(K.produtos,[]);ps.splice(i,1);save(K.produtos,ps);renderProducts();renderProductSelect(true);}
  function useProduct(i){const p=json(K.produtos,[])[i];if(!p)return;insertProduct(p,1);const ft=document.querySelector('.tab[data-tab="form"]'),fp=$("panelForm");if(ft&&fp)activate(ft,fp);resetPicker();}
  function insertSelected(){const ps=json(K.produtos,[]),s=$("prodEscolhido"),p=ps[Number(s?.value)];if(!p){alert("Escolha um produto cadastrado primeiro.");return;}insertProduct(p,Math.max(1,parseInt($("prodQtd")?.value||"1")));resetPicker();}
  function insertProduct(p,qtd=1){$("btnAddItem")?.click();const rows=document.querySelectorAll("#iList .irow"),row=rows[rows.length-1],ins=row?.querySelectorAll("input");if(ins?.length>=3){ins[0].value=p.nome;ins[1].value=qtd;ins[2].value=p.valor||"";ins[2].dispatchEvent(new Event("input",{bubbles:true}));}}
  function resetPicker(){if($("prodEscolhido"))$("prodEscolhido").value="";if($("prodQtd"))$("prodQtd").value="1";}
  function ensurePix(){if($("pixActions"))return;const pix=$("dPix");if(!pix)return;const b=document.createElement("div");b.id="pixActions";b.className="pix-actions";b.innerHTML=`<button type="button" id="btnCopiarPix">Copiar Pix</button><button type="button" id="btnWppPix">Enviar Pix no WhatsApp</button>`;pix.closest(".fgroup")?.insertAdjacentElement("afterend",b);$("btnCopiarPix").onclick=copyPix;$("btnWppPix").onclick=sendPix;}
  function pixText(){const d={tipo:$("dTipoPix")?.value||"Pix",pix:$("dPix")?.value.trim()||"",nome:$("dNomePix")?.value.trim()||"",atelie:$("dAtelie")?.value.trim()||""};if(!d.pix)return"";return`Chave Pix (${d.tipo}): ${d.pix}${d.nome?`\nNome: ${d.nome}`:""}${d.atelie?`\n${d.atelie}`:""}`;}
  function copyPix(){const t=pixText();if(!t){alert("Preencha a chave Pix primeiro.");return;}navigator.clipboard.writeText(t).then(()=>alert("Pix copiado."));}
  function sendPix(){const t=pixText();if(!t){alert("Preencha a chave Pix primeiro.");return;}const w=String($("dWpp")?.value||"").replace(/\D/g,"");window.open(`https://wa.me/${w}?text=${encodeURIComponent(t)}`,"_blank");}
  function ensureBackup(){if($("backupCard"))return;const p=$("panelDados");if(!p)return;const c=document.createElement("div");c.className="dados-card";c.id="backupCard";c.innerHTML=`<div class="sec-title">Backup dos dados</div><div class="backup-box"><p><strong>Onde os dados ficam salvos:</strong> seus dados, produtos, logomarca e orçamentos ficam guardados no navegador deste aparelho.</p><p><strong>Por que fazer backup:</strong> se limpar os dados do navegador, trocar de celular, desinstalar o app ou reinstalar, essas informações podem sumir. O backup cria um arquivo para restaurar tudo depois.</p><ul><li>Para fazer backup, toque em <strong>Baixar backup</strong> e guarde o arquivo em local seguro.</li><li>Para restaurar, instale/abra o app, entre com a senha, escolha o arquivo em <strong>Restaurar backup</strong> e confirme.</li><li>Depois de restaurar, feche e abra o app novamente.</li></ul></div><div class="fgroup" style="margin-top:12px"><label class="lbl">Lembrete de backup</label><select id="backupPeriodo"><option value="0">Sem alerta</option><option value="novo">A cada novo orçamento cadastrado</option><option value="3">A cada 3 dias</option><option value="7">A cada 7 dias</option><option value="14">A cada 14 dias</option><option value="30">A cada 30 dias</option></select></div><div class="backup-actions"><button type="button" id="btnBackup">Baixar backup</button><button type="button" id="btnMarcarBackup">Marcar como feito</button><input type="file" id="backupArquivo" accept="application/json"><button type="button" id="btnRestaurarBackup">Restaurar backup</button><button type="button" id="btnLimparHistorico">Limpar histórico</button></div><p class="backup-small" id="backupStatus"></p>`;p.insertBefore(c,p.querySelector(".senha-card"));const sv=localStorage.getItem(K.backupDias)||"0";$("backupPeriodo").value=["0","novo","3","7","14","30"].includes(sv)?sv:"7";$("backupPeriodo").onchange=()=>{localStorage.setItem(K.backupDias,$("backupPeriodo").value);backupStatus();};$("btnBackup").onclick=downloadBackup;$("btnMarcarBackup").onclick=()=>{localStorage.setItem(K.backupUltimo,new Date().toISOString());backupStatus();alert("Backup marcado como feito.");};$("btnRestaurarBackup").onclick=restoreBackup;$("btnLimparHistorico").onclick=clearHistory;backupStatus();}
  function saveBudget(status){let text=cleanPix(($("previaTexto")?.textContent||"").trim());if(!text||text.includes("Preencha o orçamento"))return;const pv=$("previaTexto");if(pv)pv.textContent=text;const item={id:Date.now().toString(36)+Math.random().toString(36).slice(2,7),criadoEm:new Date().toISOString(),status,cliente:($("fCliente")?.value||"Cliente sem nome").trim(),tema:($("fTema")?.value||"").trim(),totalTxt:($("fTotal")?.textContent||"").trim(),texto:text};const list=json(K.orcamentos,[]),old=list.find(o=>o.texto===item.texto);let isNew=false;if(old){old.status=status;old.atualizadoEm=new Date().toISOString();}else{list.unshift(item);isNew=true;}save(K.orcamentos,list.slice(0,200));renderHistory();if(localStorage.getItem(K.backupDias)==="novo"&&isNew)setTimeout(()=>alert("Lembrete: um novo orçamento foi salvo. Faça backup para proteger seus dados."),300);resetPicker();}
  function renderHistory(){const box=$("histList");if(!box)return;const q=($("histBusca")?.value||"").toLowerCase();const list=json(K.orcamentos,[]).filter(o=>!q||`${o.cliente} ${o.tema} ${o.texto}`.toLowerCase().includes(q));if(!list.length){box.innerHTML='<div class="hist-empty">Nenhum orçamento salvo ainda.</div>';return;}box.innerHTML="";list.forEach(o=>{const card=document.createElement("div");card.className="hist-card";card.innerHTML=`<div class="hist-top"><div><div class="hist-title">${esc(o.cliente||"Cliente")}</div><div class="hist-meta">${esc(o.status||"Salvo")} - ${dataBR(o.criadoEm)}${o.tema?" - "+esc(o.tema):""}</div></div><div class="hist-total">${esc(o.totalTxt||"")}</div></div><div class="hist-actions"><button type="button" data-a="ver">Ver texto</button><button type="button" data-a="copiar">Copiar</button><button type="button" data-a="whats">WhatsApp</button><button type="button" class="danger" data-a="excluir">Excluir</button></div><div class="hist-text"></div>`;const t=card.querySelector(".hist-text");t.textContent=cleanPix(o.texto||"");card.querySelector('[data-a="ver"]').onclick=()=>{t.style.display=t.style.display==="block"?"none":"block";};card.querySelector('[data-a="copiar"]').onclick=()=>navigator.clipboard.writeText(cleanPix(o.texto||"")).then(()=>alert("Orçamento copiado."));card.querySelector('[data-a="whats"]').onclick=()=>{const w=String(json(K.dados,{}).wpp||"").replace(/\D/g,"");window.open(`https://wa.me/${w}?text=${encodeURIComponent(cleanPix(o.texto||""))}`,"_blank");};card.querySelector('[data-a="excluir"]').onclick=()=>{if(confirm("Excluir este orçamento do histórico?")){save(K.orcamentos,json(K.orcamentos,[]).filter(x=>x.id!==o.id));renderHistory();}};box.appendChild(card);});}
  function clearHistory(){if(!confirm("Apagar todos os orçamentos salvos? Faça backup antes se quiser guardar."))return;localStorage.removeItem(K.orcamentos);renderHistory();alert("Histórico apagado.");}
  function downloadBackup(){const b={versao:1,criadoEm:new Date().toISOString(),dados:json(K.dados,{}),logo:localStorage.getItem(K.logo)||"",produtos:json(K.produtos,[]),orcamentos:json(K.orcamentos,[]),senha:localStorage.getItem(K.senha)||""};const url=URL.createObjectURL(new Blob([JSON.stringify(b,null,2)],{type:"application/json"}));const a=document.createElement("a");a.href=url;a.download=`orcamento-express-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);localStorage.setItem(K.backupUltimo,new Date().toISOString());backupStatus();}
  function restoreBackup(){const f=$("backupArquivo")?.files?.[0];if(!f){alert("Escolha o arquivo de backup primeiro.");return;}const r=new FileReader();r.onload=()=>{try{const b=JSON.parse(r.result);if(!confirm("Restaurar este backup? Os dados atuais serão substituídos."))return;save(K.dados,b.dados||{});save(K.produtos,b.produtos||[]);save(K.orcamentos,b.orcamentos||[]);b.logo?localStorage.setItem(K.logo,b.logo):localStorage.removeItem(K.logo);if(b.senha)localStorage.setItem(K.senha,b.senha);alert("Backup restaurado. Feche e abra o app novamente para atualizar tudo.");}catch{alert("Arquivo de backup inválido.");}};r.readAsText(f);}
  function backupStatus(){const o=$("backupStatus");if(!o)return;const v=localStorage.getItem(K.backupDias)||"0",last=localStorage.getItem(K.backupUltimo);o.textContent=last?`Último backup: ${dataBR(last)}${v==="novo"?" - alerta a cada novo orçamento":Number(v)?` - alerta a cada ${v} dias`:""}`:(v==="novo"?"Alerta configurado a cada novo orçamento cadastrado.":Number(v)?`Alerta configurado a cada ${v} dias. Nenhum backup registrado ainda.`:"Nenhum alerta de backup configurado.");}
  function checkBackup(){const v=localStorage.getItem(K.backupDias)||"0";if(!Number(v))return;const last=localStorage.getItem(K.backupUltimo),due=!last||(Date.now()-new Date(last).getTime())/86400000>=Number(v);if(due&&sessionStorage.getItem("orc_backup_alertado")!=="1"){sessionStorage.setItem("orc_backup_alertado","1");setTimeout(()=>alert("Lembrete: faça backup do Orçamento Express para proteger seus dados, produtos, logomarca e orçamentos salvos."),800);}}
  function cleanPdfText(t){return cleanPix(t).replace(/[💌👤🎉📅🚚📦🧾💰💳📌💵💸📝✨🎀]/g,"").replace(/⚠️|⚠/g,"Atenção:").replace(/•/g,"-").replace(/[—–]/g,"-").replace(/[─]+/g,"------------------------------").replace(/[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}]/gu,"").replace(/[*_`]/g,"").replace(/\n{3,}/g,"\n\n").trim();}
  async function makePdf(){const jsPDF=window.jspdf?.jsPDF;if(!jsPDF)return null;const doc=new jsPDF({unit:"mm",format:"a4"}),d=json(K.dados,{}),logo=localStorage.getItem(K.logo)||"",text=cleanPdfText($("previaTexto")?.textContent||"");let y=20;if(logo){try{doc.addImage(logo,"PNG",14,12,24,24);}catch{}}doc.setFont("helvetica","bold");doc.setFontSize(17);doc.setTextColor(140,123,255);doc.text(d.atelie||"Orçamento Express",logo?44:14,24);doc.setDrawColor(255,123,172);doc.line(14,40,196,40);y=50;doc.setTextColor(55,55,55);doc.setFontSize(11);doc.splitTextToSize(text,180).forEach(line=>{if(y>280){doc.addPage();y=18;}doc.text(line,14,y);y+=6;});return doc.output("blob");}
  async function downloadPdf(){const blob=await makePdf();if(!blob){alert("Não foi possível gerar o PDF neste navegador.");return;}const name=String($("fCliente")?.value||"orcamento").toLowerCase().replace(/[^a-z0-9]+/gi,"-").replace(/(^-|-$)/g,"")||"orcamento",url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`${name}.pdf`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);saveBudget("PDF baixado");}
  async function sharePdf(){const blob=await makePdf();if(!blob){alert("Não foi possível gerar o PDF neste navegador.");return;}const file=new File([blob],"orcamento.pdf",{type:"application/pdf"});if(navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:"Orçamento",text:"Segue o orçamento em PDF."});saveBudget("PDF compartilhado");}else alert("Este aparelho não permite compartilhar PDF direto. Use o botão Baixar PDF com logo.");}
  function intercept(){$("btnPdf")?.addEventListener("click",e=>{e.preventDefault();e.stopImmediatePropagation();downloadPdf();},true);$("btnSharePdf")?.addEventListener("click",e=>{e.preventDefault();e.stopImmediatePropagation();sharePdf();},true);$("btnWpp")?.addEventListener("click",e=>{const text=cleanPix(($("previaTexto")?.textContent||"").trim());if(!text)return;e.preventDefault();e.stopImmediatePropagation();const pv=$("previaTexto");if(pv)pv.textContent=text;saveBudget("Enviado pelo WhatsApp");const w=String(json(K.dados,{}).wpp||"").replace(/\D/g,"");window.open(`https://wa.me/${w}?text=${encodeURIComponent(text)}`,"_blank");},true);}
  function hooks(){$("btnGerar")?.addEventListener("click",()=>setTimeout(()=>{const pv=$("previaTexto");if(pv)pv.textContent=cleanPix(pv.textContent);saveBudget("Gerado");},450));$("btnSalvarProduto")?.addEventListener("click",()=>setTimeout(()=>{renderProducts();renderProductSelect(true);},200));}
  function init(){style();ensureProductsTab();ensureHistoryTab();ensurePicker();ensurePix();ensureBackup();hooks();intercept();renderHistory();checkBackup();resetPicker();}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
})();
